import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { MapleLeaf } from "@/components/maple-leaf";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { getTaxPlan } from "@/lib/api/ai-planner.functions";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Tax Planning — Maple & Ledger" },
      { name: "description", content: "Personalized RRSP, FHSA & TFSA tax plan for 2025 generated by AI, then reviewed by a Canadian accountant." },
      { property: "og:title", content: "AI Tax Planning — Maple & Ledger" },
      { property: "og:description", content: "Personalized RRSP, FHSA & TFSA tax plan for 2025." },
    ],
  }),
  component: PlannerPage,
});

const PROVS = ["ON","QC","BC","AB","MB","SK","NS","NB","NL","PE","YT","NT","NU"];

function PlannerPage() {
  const run = useServerFn(getTaxPlan);
  const [income, setIncome] = useState(95000);
  const [province, setProvince] = useState("ON");
  const [age, setAge] = useState(34);
  const [rrspRoom, setRrspRoom] = useState(18000);
  const [fhsaRoom, setFhsaRoom] = useState(8000);
  const [tfsaRoom, setTfsaRoom] = useState(7000);
  const [goals, setGoals] = useState("Buying first home in 3 years; reduce 2025 tax bill.");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<string>("");

  async function submit() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      toast.error("Please sign in to generate a plan.");
      return;
    }
    setLoading(true);
    setPlan("");
    try {
      const res = await run({ data: { income, province, age, rrspRoom, fhsaRoom, tfsaRoom, goals } });
      setPlan(res.text);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not generate plan");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-6xl px-6 pt-16 pb-24">
      <div className="flex items-center gap-3">
        <MapleLeaf className="h-7 w-7 text-primary" />
        <p className="text-xs uppercase tracking-widest text-primary">AI tax planning · 2025</p>
      </div>
      <h1 className="mt-3 font-display text-5xl md:text-6xl">
        Your personal <span className="italic text-primary">tax plan</span>.
      </h1>
      <p className="mt-4 max-w-2xl text-muted-foreground">
        Tell us about your year. Our AI drafts a CRA-aligned plan across RRSP, FHSA and TFSA — then a licensed accountant can review it with you.
      </p>

      <div className="mt-12 grid gap-10 lg:grid-cols-5">
        <div className="lg:col-span-2 space-y-5 rounded-2xl border border-border bg-card p-6">
          <Field label="Annual income">
            <MoneyInput value={income} onChange={setIncome} />
          </Field>
          <Field label="Province / territory">
            <Select value={province} onValueChange={setProvince}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>{PROVS.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent>
            </Select>
          </Field>
          <Field label="Age">
            <Input type="number" min={16} max={100} value={age} onChange={(e) => setAge(+e.target.value || 0)} />
          </Field>
          <Field label="Unused RRSP room"><MoneyInput value={rrspRoom} onChange={setRrspRoom} /></Field>
          <Field label="Unused FHSA room"><MoneyInput value={fhsaRoom} onChange={setFhsaRoom} /></Field>
          <Field label="Unused TFSA room"><MoneyInput value={tfsaRoom} onChange={setTfsaRoom} /></Field>
          <Field label="Goals / context">
            <Textarea rows={3} maxLength={800} value={goals} onChange={(e) => setGoals(e.target.value)} />
          </Field>
          <Button onClick={submit} disabled={loading} className="w-full bg-primary hover:bg-primary/90">
            <Sparkles className="h-4 w-4 mr-2" />
            {loading ? "Drafting your plan…" : "Generate plan"}
          </Button>
        </div>

        <div className="lg:col-span-3 rounded-2xl border border-border bg-paper p-6 ring-maple min-h-[400px]">
          {plan ? (
            <article className="prose prose-sm max-w-none whitespace-pre-wrap font-sans leading-relaxed">
              {plan}
            </article>
          ) : (
            <div className="flex h-full flex-col items-center justify-center text-center text-muted-foreground">
              <Sparkles className="h-10 w-10 text-primary/40 mb-4" />
              <p>Your AI-generated tax plan will appear here.</p>
              <p className="mt-2 text-xs">General information only — not a substitute for licensed tax advice. <Link to="/book" className="text-primary underline">Book a consultation</Link>.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <Label className="mb-2 block">{label}</Label>
      {children}
    </div>
  );
}

function MoneyInput({ value, onChange }: { value: number; onChange: (n: number) => void }) {
  return (
    <div className="relative">
      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
      <Input type="number" min={0} step={500} value={value}
        onChange={(e) => onChange(Number(e.target.value) || 0)} className="pl-7" />
    </div>
  );
}
